// ============================================================================
//   Ver  :| Author					:| Mod. Date :| Changes Made:
//   V1.1 :| Alexandra Du			:| 06/01/2016:| Added Verilog file
// ============================================================================


//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

//`define ENABLE_ADC_CLOCK
`define ENABLE_CLOCK1
//`define ENABLE_CLOCK2
//`define ENABLE_SDRAM
`define ENABLE_HEX0
//`define ENABLE_HEX1
//`define ENABLE_HEX2
//`define ENABLE_HEX3
//`define ENABLE_HEX4
//`define ENABLE_HEX5
//`define ENABLE_KEY
`define ENABLE_LED
`define ENABLE_SW
//`define ENABLE_VGA
//`define ENABLE_ACCELEROMETER
//`define ENABLE_ARDUINO
`define ENABLE_GPIO

module DE10_LITE_Golden_Top(

	//////////// ADC CLOCK: 3.3-V LVTTL //////////
`ifdef ENABLE_ADC_CLOCK
	input 		          		ADC_CLK_10,
`endif
	//////////// CLOCK 1: 3.3-V LVTTL //////////
`ifdef ENABLE_CLOCK1
	input 		          		MAX10_CLK1_50,
`endif
	//////////// CLOCK 2: 3.3-V LVTTL //////////
`ifdef ENABLE_CLOCK2
	input 		          		MAX10_CLK2_50,
`endif

	//////////// SDRAM: 3.3-V LVTTL //////////
`ifdef ENABLE_SDRAM
	output		    [12:0]		DRAM_ADDR,
	output		     [1:0]		DRAM_BA,
	output		          		DRAM_CAS_N,
	output		          		DRAM_CKE,
	output		          		DRAM_CLK,
	output		          		DRAM_CS_N,
	inout 		    [15:0]		DRAM_DQ,
	output		          		DRAM_LDQM,
	output		          		DRAM_RAS_N,
	output		          		DRAM_UDQM,
	output		          		DRAM_WE_N,
`endif

	//////////// SEG7: 3.3-V LVTTL //////////
`ifdef ENABLE_HEX0
	output		     [7:0]		HEX0,
`endif
`ifdef ENABLE_HEX1
	output		     [7:0]		HEX1,
`endif
`ifdef ENABLE_HEX2
	output		     [7:0]		HEX2,
`endif
`ifdef ENABLE_HEX3
	output		     [7:0]		HEX3,
`endif
`ifdef ENABLE_HEX4
	output		     [7:0]		HEX4,
`endif
`ifdef ENABLE_HEX5
	output		     [7:0]		HEX5,
`endif

	//////////// KEY: 3.3 V SCHMITT TRIGGER //////////
`ifdef ENABLE_KEY
	input 		     [1:0]		KEY,
`endif

	//////////// LED: 3.3-V LVTTL //////////
`ifdef ENABLE_LED
	output		     [9:0]		LEDR,
`endif

	//////////// SW: 3.3-V LVTTL //////////
`ifdef ENABLE_SW
	input 		     [9:0]		SW,
`endif

	//////////// VGA: 3.3-V LVTTL //////////
`ifdef ENABLE_VGA
	output		     [3:0]		VGA_B,
	output		     [3:0]		VGA_G,
	output		          		VGA_HS,
	output		     [3:0]		VGA_R,
	output		          		VGA_VS,
`endif

	//////////// Accelerometer: 3.3-V LVTTL //////////
`ifdef ENABLE_ACCELEROMETER
	output		          		GSENSOR_CS_N,
	input 		     [2:1]		GSENSOR_INT,
	output		          		GSENSOR_SCLK,
	inout 		          		GSENSOR_SDI,
	inout 		          		GSENSOR_SDO,
`endif

	//////////// Arduino: 3.3-V LVTTL //////////
`ifdef ENABLE_ARDUINO
	inout 		    [15:0]		ARDUINO_IO,
	inout 		          		ARDUINO_RESET_N,
`endif

	//////////// GPIO, GPIO connect to GPIO Default: 3.3-V LVTTL //////////
`ifdef ENABLE_GPIO
	inout 		    [35:0]		GPIO
`endif
);

//=======================================================
//  REG/WIRE declarations
//=======================================================

	localparam BAUD_RATE = 115200;

	wire rst_n;
	wire [9:0] led;

	// localparam CLK_FREQ  = 50_000_000;
	// localparam BAUD_RATE = 115200;
	// localparam baud_reg = (CLK_FREQ)/(BAUD_RATE*16) - 1;

	// wire rst_n, tx_fifo_not_full, rx_fifo_have_data, st_tx, ld_rx;
	// wire [7:0] tx_data, rx_data;

//=======================================================
//  Structural coding
//=======================================================

	assign rst_n     = SW[0];
	assign LEDR[0]   = SW[0];

	top  #(
		.CLK_FREQ (50_000_000),
	    .BAUD_RATE(BAUD_RATE)
	) system_test (
	    .i_clk(MAX10_CLK1_50),
	    .i_rst_n(rst_n),
	    //.i_rx_serial(ARDUINO_IO[0]),
	    //.o_tx_serial(ARDUINO_IO[1]),
		.i_rx_serial(GPIO[0]),
	    .o_tx_serial(GPIO[1]),
		.o_hex_class(HEX0[7:0]),
		.o_hex_state(),
	    .o_led(led)
	);

	// assign rst_n = SW[0];
	// assign LEDR  = SW;

	// assign tx_data = rx_data;
	// assign st_tx   = rx_fifo_have_data & tx_fifo_not_full;
	// assign ld_rx   = rx_fifo_have_data & tx_fifo_not_full;

	// uart_top uart_ip (
    // //GLOBAL SIGNALS
    //     .i_clk(MAX10_CLK1_50), // 50MHz clock
    //     .i_rst_n(rst_n), // Active low reset
    // //CONTROL SIGNALS
    //     .i_rx_en(1'b1),
    //     .i_tx_en(1'b1),
    //     .i_width_sel(2'b11),        // 8 bit
    //     .i_parity_sel(3'b0),        // no parity bit
    //     .i_stop_sel(1'b0),          // 1 bit stop
    //     .i_baud_rate_value(baud_reg), // 19200bps
    //     //.i_baud_rate_value(24'd1),  // 1562500bps
    // //FLAG RESPONSE SIGNALS
    //     .o_tx_data_avail(tx_fifo_not_full),  // can store data in TX FIFO
    //     .o_rx_data_avail(rx_fifo_have_data), // can load  data in RX FIFO

    //     .o_e_overrun_flag(),// error overrun flag
    //     .o_e_parity_flag(), // error parity flag
    //     .o_e_frame_flag(),  // error frame flag

    // //IO SIGNALS
    //     .i_rx_serial(ARDUINO_IO[0]), // UART RX line in
    //     .o_tx_serial(ARDUINO_IO[1]), // UART TX line out
    //     .i_load_uart(ld_rx),       // load signal from RX FIFO
    //     .i_store_uart(st_tx),      // store signal to TX FIFO
    //     .i_trans_data(tx_data),    // tx data send
    //     .o_receive_data(rx_data)   // rx data receive
    // );

endmodule
